# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "host" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "host"
    node.vm.network :private_network, ip: "192.168.100.10"

    # execute itamae provision #
    ############################
    node.vm.provision :itamae do |itamae|
      itamae.sudo = true
      itamae.shell = '/bin/sh'
      itamae.json = '../nodes/node.json'
      itamae.recipes = '../roles/host.rb'
    end
  end
  config.vm.define "target" do |node|
    node.vm.box = "ubuntu/bionic64"
    node.vm.hostname = "target"
    node.vm.network :private_network, ip: "192.168.100.20"
  end
end
